namespace WinOptimizationTool.Functions.Registry.Application;

public class MsftBloat : BaseFunction
{
    [NotImplemented]
    public static Result Uninstall()
	{
		var list = new List<Result>()
		{
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.3DBuilder\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.AppConnector\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.BingFinance\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.BingFoodAndDrink\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.BingHealthAndFitness\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.BingMaps\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.BingNews\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.BingSports\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.BingTranslator\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.BingTravel\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.BingWeather\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.CommsPhone\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.ConnectivityStore\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.FreshPaint\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.GetHelp\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.Getstarted\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.HelpAndTips\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.Media.PlayReadyClient.2\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.Messaging\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.Microsoft3DViewer\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.MicrosoftOfficeHub\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.MicrosoftPowerBIForWindows\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.MicrosoftSolitaireCollection\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.MicrosoftStickyNotes\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.MinecraftUWP\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.MixedReality.Portal\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.MoCamera\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","# Get-AppxPackage \"Microsoft.MSPaint\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.NetworkSpeedTest\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.OfficeLens\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.Office.OneNote\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.Office.Sway\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.OneConnect\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.People\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.Print3D\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.Reader\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","# Get-AppxPackage \"Microsoft.RemoteDesktop\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.SkypeApp\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.Todos\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.Wallet\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.WebMediaExtensions\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.Whiteboard\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.WindowsAlarms\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.WindowsCamera\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"microsoft.windowscommunicationsapps\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.WindowsFeedbackHub\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.WindowsMaps\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.WindowsPhone\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","# Get-AppxPackage \"Microsoft.Windows.Photos\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.WindowsReadingList\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.WindowsScan\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.WindowsSoundRecorder\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.WinJS.1.0\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.WinJS.2.0\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.YourPhone\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.ZuneMusic\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","# Get-AppxPackage \"Microsoft.ZuneVideo\" | Remove-AppxPackage"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage \"Microsoft.Advertising.Xaml\" | Remove-AppxPackage # Dependency for microsoft.windowscommunicationsapps, Microsoft.BingWeather"),
		};
		return list.ToSingleResult("UninstallMsftBloat");
	}
    [NotImplemented]
    public static Result Install()
	{
		var list = new List<Result>()
		{
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.3DBuilder\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.Advertising.Xaml\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"} # Dependency for microsoft.windowscommunicationsapps, Microsoft.BingWeather"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.AppConnector\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.BingFinance\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.BingFoodAndDrink\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.BingHealthAndFitness\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.BingMaps\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.BingNews\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.BingSports\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.BingTranslator\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.BingTravel\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.BingWeather\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.CommsPhone\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.ConnectivityStore\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.FreshPaint\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.GetHelp\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.Getstarted\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.HelpAndTips\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.Media.PlayReadyClient.2\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.Messaging\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.Microsoft3DViewer\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.MicrosoftOfficeHub\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.MicrosoftPowerBIForWindows\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.MicrosoftSolitaireCollection\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.MicrosoftStickyNotes\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.MinecraftUWP\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.MixedReality.Portal\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.MoCamera\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.MSPaint\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.NetworkSpeedTest\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.OfficeLens\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.Office.OneNote\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.Office.Sway\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.OneConnect\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.People\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.Print3D\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.Reader\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.RemoteDesktop\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.SkypeApp\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.Todos\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.Wallet\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.WebMediaExtensions\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.Whiteboard\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.WindowsAlarms\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.WindowsCamera\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.windowscommunicationsapps\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.WindowsFeedbackHub\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.WindowsMaps\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.WindowsPhone\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.Windows.Photos\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.WindowsReadingList\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.WindowsScan\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.WindowsSoundRecorder\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.WinJS.1.0\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.WinJS.2.0\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.YourPhone\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.ZuneMusic\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
			Result.MultipleErrors("Not Implemented","Get-AppxPackage -AllUsers \"Microsoft.ZuneVideo\" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
		};
		return list.ToSingleResult("InstallMsftBloat");
	}
}
